##############################################################################################################################
# # Cleanup:
#const sleep = ms => () => new Promise((resolve, reject) => window.setTimeout(resolve, ms));
#Promise.resolve()
#.then(() => {  document.getElementsByClassName("details-overlay details-reset position-relative d-inline-block ")[3].children[0].click();  })
#.then(sleep(500))
#.then(() => {  document.getElementsByClassName("dropdown-item btn-link menu-item-danger")[0].click();  })
#.then(sleep(1000))
#.then(() => {  document.getElementsByClassName("btn btn-block btn-danger")[0].click();});
#
# while [ 1 ] ; do sleep 4; xdotool key Up; sleep 0.1; xdotool key Return; done
##############################################################################################################################

name: "CI"

on: [push, pull_request]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci skip') && (!contains(github.event_name, 'pull_request') || (contains(github.event_name, 'pull_request') && github.event.pull_request.head.repo.full_name != github.repository))"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout: Code"
      uses: actions/checkout@v4

    - name: "Checkout: Code (PR)"
      uses: actions/checkout@v4
      if: "contains(github.event_name, 'pull_request')"
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: "Setup: Java"
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: "temurin"

    - name: "Setup: Install additional dependencies"
      run: sudo apt-get install -y ispell

    - name: "Cache: Gradle"
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle
          .gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.*') }}

    - name: "Build: Project with make"
      run: make clean all

    - name: "Build: List dist files"
      if: always()
      run: find dist -type f -maxdepth 2

    - name: "Artifacts: All"
      if: always()
      uses: actions/upload-artifact@v2.2.1
      with:
        name: "all"
        path: dist
        retention-days: 5

    - name: "Artifacts: Android APK"
      uses: actions/upload-artifact@v2.2.1
      with:
        name: "android-apk"
        path: |
          dist/*.apk
